name: .NET WPF CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish App
      run: dotnet publish -c Release -r win-x64 --self-contained false -o ./publish_output

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DncApp-Release-Build
        path: ./publish_output/